### PR TITLE
feat: adds `codeMirrorLoaded` that fires after codeMirror set

### PR DESCRIPTION
**Pull request by sp90**
This solves: #145

### CODE REVIEW

**Comment by sp90** [comment]
Problem with using 

```ts
  @ViewChild(CodeMirrorComponent) set editor(editor: CodeMirrorComponent) {
    console.log('editor.codeMirror: ', editor.codeMirror);
  }
```

is that codeMirror is not set here, but only after the codeMirror instance is set which is afterViewInit, so this happens after view child is initiated

And to avoid clunky `setTimout` code i think its is a quality of life improvement needed to be added

**Comment by scttcper** [comment]
seeing a type error
```
Error: src/lib/codemirror.component.ts:131:12 - error TS2339: Property 'onLoad' does not exist on type 'CodemirrorComponent'.
```

**Comment by sp90** [comment]
@scttcper its been solved

**Pull request merged**
